### ISSUE TITLE
Unable to build in Ubuntu Linux (gcc 7.2.0)

### ISSUE THREAD

**Issue by manelio** [leviarcoin/leviarcoin-src#4]
```
leviarcoin-src/external/miniupnpc/upnpc.c:130:23: error: ‘%d’ directive output may be truncated writing between 1 and 10 bytes into a region of size 6 [-Werror=format-truncation=]
   snprintf(index, 6, "%d", i);
                       ^~
```

**Comment by leviarcoin** [comment]
Seems related to gcc > 7.1 issue, try to build with gcc 5.4.0
